name: Builds
on: [push]
jobs:
  linux-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux
          path: minivm
  macos-opt:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-mac
          path: minivm