name: Builds
on: [push]
jobs:
  linux-minivm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux
          path:  | 
            bin/minivm
            bin/minivm-color
            bin/minivm-dis
  macos-minivm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-mac
          path: | 
            bin/minivm
            bin/minivm-color
            bin/minivm-dis
  windows-minivm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-windows.exe
          path:  | 
            bin/minivm.exe
            bin/minivm-color.exe
            bin/minivm-dis.exe